######################################################################
# Automatically generated by qmake (2.01a) Thu May 22 22:14:05 2014
######################################################################

TEMPLATE = app
TARGET = qtracer
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
